/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Event =
    | "branch_protection_rule"
    | "check_run"
    | "check_suite"
    | "create"
    | "delete"
    | "deployment"
    | "deployment_status"
    | "discussion"
    | "discussion_comment"
    | "fork"
    | "gollum"
    | "issue_comment"
    | "issues"
    | "label"
    | "merge_group"
    | "milestone"
    | "page_build"
    | "project"
    | "project_card"
    | "project_column"
    | "public"
    | "pull_request"
    | "pull_request_review"
    | "pull_request_review_comment"
    | "pull_request_target"
    | "push"
    | "registry_package"
    | "release"
    | "status"
    | "watch"
    | "workflow_call"
    | "workflow_dispatch"
    | "workflow_run"
    | "repository_dispatch";