export type PredefinedActions =
    'actions/cache@v3' |
    'actions/cache@v4' |
    'actions/checkout@v3' |
    'actions/checkout@v4' |
    'actions/download-artifact@v3' |
    'actions/download-artifact@v4' |
    'actions/first-interaction@v1' |
    'actions/github-script@v3' |
    'actions/github-script@v4' |
    'actions/github-script@v5' |
    'actions/github-script@v6' |
    'actions/github-script@v7' |
    'actions/labeler@v3' |
    'actions/labeler@v4' |
    'actions/labeler@v5' |
    'actions/setup-dotnet@v3' |
    'actions/setup-dotnet@v4' |
    'actions/setup-go@v3' |
    'actions/setup-go@v4' |
    'actions/setup-go@v5' |
    'actions/setup-java@v3' |
    'actions/setup-java@v4' |
    'actions/setup-node@v3' |
    'actions/setup-node@v4' |
    'actions/setup-python@v3' |
    'actions/setup-python@v4' |
    'actions/setup-python@v5' |
    'actions/upload-artifact@v3' |
    'actions/upload-artifact@v4'
