name: workflow-1
on:
  discussion_comment:
    types:
      - created
      - edited
  pull_request:
    types:
      - opened
      - unlocked
      - opened
      - review_requested
    branches:
      - master
    paths: []
  workflow_dispatch: {}
jobs:
  nice-job:
    name: job-1
    runs-on: ubuntu-latest
    steps:
      - name: step-1
        id: id-0
        shell: bash
        run: echo 1
